name: Test
on:
  push:
permissions:
  actions: write
  contents: read
jobs:
  python-coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
    - uses: nixbuild/nix-quick-install-action@v31
      with:
        nix_conf: keep-outputs = true
    - uses: nix-community/cache-nix-action@v6
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
        restore-prefixes-first-match: nix-${{ runner.os }}-
        purge: true
        purge-prefixes: nix-${{ runner.os }}-
        purge-created: 0
        purge-last-accessed: 0
        purge-primary-key: never
    - uses: wntrblm/nox@2254a1ee500bbf66c2a5e4ff5dad030b9f579dcd
    - working-directory: lang/python/test
      run: nox -s coverage
