name: Test
on:
  push:
permissions:
  contents: read
jobs:
  build-lib:
    uses: ./.github/workflows/lib.yaml
    permissions:
      actions: write
      contents: read
  python-coverage:
    needs: build-lib
    name: Test Coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@v6
    - uses: actions/download-artifact@v4
      with:
        name: lib-ubuntu-latest
        path: lang/python/artifacts
    - name: Copy built library to package
      run: cp -r lang/python/artifacts/lib lang/python/mvsr/lib
    - uses: wntrblm/nox@main
    - name: Run coverage tests
      working-directory: lang/python/test
      run: nox -s coverage
