name: Build and Test Python
on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: ubuntu-latest
      build_wheel:
        type: boolean
        default: false
      nox-session:
        type: string
jobs:
  test:
    name: >-
      ${{
        inputs.build_wheel && 'Build ' || ''
      }}${{
        inputs.build_wheel && inputs.nox-session != '' && 'and ' || ''
      }}${{
        inputs.nox-session != '' && format('Test Python ({0})', inputs.nox-session) || ''
      }}
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: lib-${{ inputs.runner }}
          path: ${{ runner.temp }}/artifact
      - name: Copy built library to package
        shell: bash
        run: |
          cp -r $RUNNER_TEMP/artifact/${{ runner.os != 'Windows' && 'lib' || 'bin' }} \
            lang/python/mvsr/lib
      - name: Build wheel
        if: inputs.build_wheel
        working-directory: lang/python
        run: uv build --wheel
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: inputs.build_wheel
        with:
          name: python-${{ inputs.runner }}
          path: lang/python/dist/*.whl
      - uses: wntrblm/nox@97e345e6a26bb2c5aacff9cc4327bd4ac1b00ce6 # 2026.04.10
        if: ${{ inputs.nox-session != '' && !(runner.os == 'Windows' && runner.arch == 'ARM64') }}
      - name: Run nox session
        if: ${{ inputs.nox-session != '' && !(runner.os == 'Windows' && runner.arch == 'ARM64') }}
        working-directory: lang/python/test
        run: nox -s "${{ inputs.nox-session }}"
